# Generated by Django 2.2.1 on 2019-05-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='rollno',
            new_name='rollNo',
        ),
    ]
